#include <vtkAutoInit.h>

#include <vtkCamera.h>
#include <vtkDataSetMapper.h>
#include <vtkSmartPointer.h>
#include <vtkSphereSource.h>
#include <vtkPolyDataMapper.h>
#include <vtkActor.h>
#include <vtkRenderer.h>
#include <vtkRenderWindow.h>
#include <vtkRenderWindowInteractor.h>
#include <vtkInteractorStyleTrackballCamera.h>
#include <vtkGenericRenderWindowInteractor.h>
#include <vtkObjectFactory.h>
#include <vtkProperty.h>
#include <vtkAxesActor.h>
#include <vtkOrientationMarkerWidget.h>
#include <vtkNew.h>
#include <vtkArrowSource.h>
#include <vtkTransform.h>
#include <vtkAxes.h>
#include <vtkCylinderSource.h>
#include <vtkPointData.h>
#include <vtkPolyData.h>
#include <vtkDoubleArray.h>
#include <vtkSmartPointer.h>
#include <vtkRenderer.h>
#include <vtkRenderWindow.h>
#include <vtkRenderWindowInteractor.h>
#include <vtkGenericOpenGLRenderWindow.h>
#include <vtkPLYReader.h>
#include <vtkXMLPolyDataReader.h>
#include <vtkOBJReader.h>
#include <vtkSTLReader.h>
#include <vtkPolyDataReader.h>
#include <vtkBYUReader.h>
#include <vtkTubeFilter.h>
#include <vtkGlyph3D.h>
#include <vtkNamedColors.h>
#include <vtkTransformPolyDataFilter.h>
#include <vtkParametricMobius.h>
#include <vtkParametricFunctionSource.h>
#include <vtkMath.h>